# Generated by Django 4.0.1 on 2022-01-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producst',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
