# Generated by Django 4.0.1 on 2022-01-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_producst_ispaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producst',
            old_name='isPaid',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='producst',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producst',
            name='price',
        ),
        migrations.AddField(
            model_name='producst',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producst',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='producst',
            name='description',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name='producst',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
